import Head from "next/head";
import Image from "next/image";
import FootballField from "../public/FootballField.png";

export default function Home() {
    return (
        <>
            <Head>
                <title>Sheil Gandhi</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="h-screen">
                <div className="absolute -z-10 h-screen w-screen border-b-2 border-lime-700	">
                    <Image
                        fill
                        src={FootballField}
                        quality={100}
                        alt="Football Field"
                    />
                </div>
                <div> Coach </div>
            </div>
        </>
    );
}
